Much improved logic for file edit/view. Experimental remote HOME directory.

diff --git a/panssh b/panssh
--- a/panssh
+++ b/panssh
@@ -116,9 +116,8 @@ fi
 
 # --- File transfer between local and host ---
 transfer_file() {
-    local from="$1"
-    local to="$2"
-    scp $SCP_OPTIONS "$from" "$to"
+    scp $SCP_OPTIONS "$1" "$2"
+    return $?
 }
 
 # --- Remote edit command handler ---
@@ -139,9 +138,11 @@ launch_editor() {
     fi
 }
 
-view_remote_file() {
-    local remote_path="$1"
-    shift
+# --- Edit or view a remote file ---
+edit_file() {
+    local action="$1"
+    local remote_path="$2"
+    shift 2
     local editor_args=("$@")
 
     # Resolve full remote path
@@ -149,79 +150,75 @@ view_remote_file() {
         remote_path="$current_dir/$remote_path"
     fi
 
-    # Create a temp file for local editing
-    local local_file
-    local_file="$(mktemp $PANSSH_TEMP_DIR/panssh-edit.XXXXXX)"
+    local can_edit=0
+    local download_needed=0
 
-    # Download file from remote if it exists
-    if ! ssh_exec "[ -f \"$remote_path\" ]"; then
-        echo "❓ File not found."
-        return 1
-    elif ! ssh_exec "[ -r \"$remote_path\" ]"; then
-        echo "🚫 File is not readable."
-        return 1
-    else
-        transfer_file "$USER@$HOST:$remote_path" "$local_file"
-    fi
-
-    # Run editor
-    launch_editor "$local_file" "${editor_args[@]}"
-    rm -f "$local_file"
-}
-
-edit_remote_file() {
-    local remote_path="$1"
-    shift
-    local editor_args=("$@")
-
-    # Resolve full remote path
-    if [[ "$remote_path" != /* ]]; then
-        remote_path="$current_dir/$remote_path"
-    fi
-
-    # Create a temp file for local editing
-    local local_file
-    local_file="$(mktemp $PANSSH_TEMP_DIR/panssh-edit.XXXXXX)"
-
-    # Download file from remote if it exists
-    if ssh_exec "[ -f \"$remote_path\" ]"; then
-        if ! ssh_exec "[ -r \"$remote_path\" ]"; then
+    if ssh_exec "[ -e \"$remote_path\" ]"; then
+        # Path exists - check what's there.
+        if ssh_exec "[ -d \"$remote_path\" ]"; then
+            echo "🟡 Path is a directory."
+        elif ! ssh_exec "[ -f \"$remote_path\" ]"; then
+            echo "🟡 Not a regular file."
+        elif ! ssh_exec "[ -r \"$remote_path\" ]"; then
             echo "🚫 File is not readable."
-            return 1
-        fi
-
-        if ! ssh_exec "[ -w \"$remote_path\" ]"; then
+        elif [[ "$action" == "ed" ]] && ! ssh_exec "[ -w \"$remote_path\" ]"; then
             echo "🚫 File is not writable."
-            return 1
         else
-            transfer_file "$USER@$HOST:$remote_path" "$local_file"
+            can_edit=1  
+            download_needed=1
         fi
     else
+        # No existing file - check we can create it.
         local dirname=$(dirname "$remote_path")
-        if ! ssh_exec "[ -w \"$dirname\" ]"; then
+        if ! ssh_exec "[ -d \"$dirname\" ]"; then
+            echo "🚫 Directory not found."
+        elif ! ssh_exec "[ -w \"$dirname\" ]"; then
             echo "🚫 Directory is not writable."
-            return 1
-        fi 
+        else
+            can_edit=1  
+        fi
     fi
 
-    # Get initial checksum
-    local sum_before
-    sum_before=$(shasum "$local_file" | awk '{print $1}')
+    # Return now if we can't edit the requested file.
+    (( can_edit == 1 )) || return 1
+
+    # Create a temporary file for local editing.
+    local filename=$(basename "$remote_path")
+    local local_file
+
+    if ! local_file="$(mktemp $PANSSH_TEMP_DIR/$filename.XXXXXX)"; then
+        echo "❌ Failed to create local temporary file."
+        return 1
+    fi
+
+    # Download the file, if needed.
+    if (( download_needed == 1 )); then
+        if ! transfer_file "$USER@$HOST:$remote_path" "$local_file"; then
+            echo "❌ Failed to download file."
+            rm -f "$local_file"
+            return 1
+        fi
+    fi
+
+    # Get checksum before editing.
+    local sum_before=$(shasum "$local_file" | awk '{print $1}')
 
     # Run editor
     if launch_editor "$local_file" "${editor_args[@]}"; then
-        # Get new checksum.
-        local sum_after
-        sum_after=$(shasum "$local_file" | awk '{print $1}')
-
-        if [[ "$sum_after" == "$sum_before" ]]; then
-            echo "🟡 File has not changed."
-        else
-            transfer_file "$local_file" "$USER@$HOST:$remote_path"
+        if [[ "$action" == "ed" ]]; then
+            # Check whether file has changed: get new checksum.
+            local sum_after=$(shasum "$local_file" | awk '{print $1}')
+            # If changed, upload the file
+            if [[ "$sum_after" != "$sum_before" ]]; then
+                transfer_file "$local_file" "$USER@$HOST:$remote_path"
+            else
+                echo "🟡 File has not changed."
+            fi
         fi
     fi
 
     rm -f "$local_file"
+    return 0
 }
 
 # -------- Interactive operation --------
@@ -233,7 +230,21 @@ echo -e "\nConnected to $SITE_NAME.$ENV_ID\n"
 auto_ls=0
 current_status=0
 current_dir="/code"
-ssh_exec "cd $current_dir"
+
+# Basic environment checks.
+if ssh_exec "cd $current_dir"; then
+    if ssh_exec "[ -w $current_dir ]"; then
+        echo "🟡 $current_dir directory is writable."
+        echo -e "You may want to switch to Git mode before continuing.\n"
+    else
+        echo "🚫 $current_dir directory is read-only."
+        echo -e "You may want to switch to SFTP mode before continuing.\n"
+    fi
+fi
+
+if ! PANSSH_HOME=$(ssh_exec "mktemp -d /tmp/panssh-home.XXXXXX"); then
+    echo "❌ Failed create to remote HOME directory."
+fi
 
 interrupted=0
 trap 'interrupted=1' SIGINT
@@ -257,11 +268,7 @@ while true; do
         action="${BASH_REMATCH[1]}"
         file_path="${BASH_REMATCH[2]}"
         read -ra editor_args <<< "${BASH_REMATCH[3]}"
-        if [[ "$action" == "ed" ]]; then
-            edit_remote_file "$file_path" "${editor_args[@]}"
-        else
-            view_remote_file "$file_path" "${editor_args[@]}"
-        fi
+        edit_file "$action" "$file_path" "${editor_args[@]}"
         continue
     fi
 
@@ -279,7 +286,7 @@ while true; do
 
     # Run the command in the correct directory
     current_dir_before="$current_dir"
-    ssh_exec_track "cd \"$current_dir\" && $cmd"
+    ssh_exec_track "export HOME=\"$PANSSH_HOME\"; cd \"$current_dir\" && $cmd"
     current_status=$?
 
     # Automatic directory listing if enabled and directory was changed.
