Refactor: moved interactive mode code into new `interactive` function. Changed scope of related variables to local.

diff --git a/panssh b/panssh
--- a/panssh
+++ b/panssh
@@ -111,19 +111,21 @@ ssh_exec_track() {
     # Build command parts.
     local setup_cmd="$1"
     local cmd="$2"
+    local status="$3"
 
-    # Run setup and main commands. Write PID and CWD files.
+    # Run setup and main commands. Write PID and CWD to files on remote.
     ssh_exec "
         $setup_cmd
         echo \$\$ > $REMOTE_PID_FILE
+        bash -c \"exit $status\"
         $cmd
         status=\$?
         echo \$PWD > $REMOTE_CWD_FILE
         exit \$status
     "
-    local status=$?
+    status=$?
 
-    # Our ssh process may have been interrupted (e.g. by Ctrl-C),
+    # Our SSH process may have been interrupted (e.g. by Ctrl-C),
     # so we attempt to terminate the remote sub-process anyway.
     # Then retrieve and output the final working directory.
     REMOTE_CWD=$(ssh_exec "
@@ -144,15 +146,17 @@ ssh_exec_track() {
 cleanup() {
     local final_status=$?
 
-    # Remove remote temporary files.
-    ssh_exec "rm -f $REMOTE_CWD_FILE $REMOTE_PID_FILE"
+    if (( INTERACTIVE_MODE == 1 )); then
+        # Remove remote temporary files, save command history.
+        ssh_exec "rm -f $REMOTE_CWD_FILE $REMOTE_PID_FILE"
+        history -a
+    fi
 
-    # Close the SSH connection.
+    # Attempt to close the SSH connection.
     ssh -O exit $SSH_OPTIONS "$USER@$HOST" 2>/dev/null
     local status=$?
 
     if (( INTERACTIVE_MODE == 1 )); then
-        history -a
         if (( status == 0 )); then
             echo -e "\nConnection to $SITE_NAME.$ENV_ID closed." >&2
         else
@@ -176,7 +180,6 @@ if [[ $# -gt 1 ]] || ! [ -t 0 ]; then
     ssh_exec "$REMOTE_ENV; $cmd"
     exit $?
 fi
-readonly INTERACTIVE_MODE=1
 
 # --- File transfer between local and host ---
 transfer_file() {
@@ -352,171 +355,187 @@ handle_copyr() {
 
 # -------- Interactive operation --------
 
-# First, check that we can connect successfully.
-ssh_exec "exit" || exit $?
-echo -e "\n$PANSSH_VERSION: Connected to $SITE_NAME.$ENV_ID\n" >&2
+interactive() {
 
-# Check for Bash version 4+.
-if ! ( [[ $BASH_VERSION =~ ^([0-9]+)\. ]] && (( ${BASH_REMATCH[1]} >= 4 )) ) then
-    echo -e "ℹ️  Tab-completion in PanSSH requires Bash 4+\n" >&2
-else
-    # Find our readx script.
-    readonly READX="readx.source.sh"
-    READX_PATH="$SCRIPT_DIR/$READX"
-    if [[ ! -f "$READX_PATH" ]]; then
-        READX_PATH="$SCRIPT_DIR/../lib/panssh/$READX"
+    local status
+
+    # First, check that we can connect successfully.
+    if ! ssh_exec "exit"; then
+        status=$?
+        echo -e "\n$PANSSH_VERSION: Failed to connect to $SITE_NAME.$ENV_ID\n" >&2
+        exit $status
     fi
 
-    if [[ ! -f "$READX_PATH" ]]; then
-        echo -e "ℹ️  Failed to find $READX. Tab-completion will not be available.\n" >&2
-        unset READX_PATH
+    echo -e "\n$PANSSH_VERSION: Connected to $SITE_NAME.$ENV_ID\n" >&2
+    readonly INTERACTIVE_MODE=1
+
+    # Check for Bash version 4+.
+    if ! ( [[ $BASH_VERSION =~ ^([0-9]+)\. ]] && (( ${BASH_REMATCH[1]} >= 4 )) ) then
+        echo -e "ℹ️  Tab-completion in PanSSH requires Bash 4+\n" >&2
     else
-        readonly READX_PATH
-    fi
-fi
+        # Find our readx script.
+        readonly READX="readx.source.sh"
+        READX_PATH="$SCRIPT_DIR/$READX"
+        if [[ ! -f "$READX_PATH" ]]; then
+            READX_PATH="$SCRIPT_DIR/../lib/panssh/$READX"
+        fi
 
-# Get local colour settings.
-readonly clr0=$(tput sgr0 2>/dev/null) \
-&& readonly clr1=$(tput setaf 1 2>/dev/null) \
-&& readonly clr2=$(tput setaf 3 2>/dev/null) \
-&& readonly clr3=$(tput setaf 6 2>/dev/null)
-
-# Escaped prompt used, with readx (bash command line input).
-readonly prompt_ps1=$( printf \
-    "\[${clr1}\]%s\[${clr0}\].\[${clr2}\]%s\[${clr0}\]:\[${clr3}\]%s\[${clr0}\]\$ " \
-    "$SITE_NAME" "$ENV_ID" "_CWD_"
-)
-
-# Get un-escaped prompt, used with `echo` and `read`.
-tmp=${prompt_ps1//\\[/}
-readonly prompt=${tmp//\\]/}
-
-# Set up command history behaviour.
-export HISTFILE="$STORAGE_DIR/$SITE_NAME.$ENV_ID.history"
-export HISTCONTROL=ignorespace:ignoredups:erasedups
-history -r
-
-# Set up initial state.
-REMOTE_CWD="/code"
-current_dir="$REMOTE_CWD"
-current_status=0
-auto_ls=0
-
-# Basic environment checks.
-if ssh_exec "cd $current_dir"; then
-    if ssh_exec "[ -w $current_dir ]"; then
-        echo -e "🟡 $current_dir directory is writable (SFTP mode)\n" >&2
-    else
-        echo -e "🚫 $current_dir directory is read-only (Git mode)\n" >&2
-    fi
-fi
-
-# Create our remote home directory if it doesn't exist.
-ssh_exec "mkdir -p \"$REMOTE_HOME\""
-
-# --- Main loop ---
-trap '' SIGINT
-while true; do
-    if [[ -n "$READX_PATH" ]]; then
-        # readx is available - use it for command input.
-        export READX_EXEC="ssh $SSH_OPTIONS $USER@$HOST 'echo %s | bash'"
-        export REMOTE_ENV CWD="$current_dir"
-        export READX_PROMPT="${prompt_ps1/_CWD_/$current_dir}"
-        export READX_FIRST_TIME="${READX_FIRST_TIME:-1}"
-
-        # Use bash interactive to read command input with completion.
-        cmd=$(/usr/bin/env bash --init-file "$READX_PATH")
-        # Re-display both prompt and input, to mimic standard Bash behaviour.
-        echo "${prompt/_CWD_/$current_dir}$cmd"
-        READX_FIRST_TIME=0
-    else
-        # readx is not available - use `read` for command input.
-        cmd=$(
-            trap - SIGINT
-            bind '"\t":' 2>/dev/null
-            read -e -r -p "${prompt/_CWD_/$current_dir}" cmd && echo $cmd
-        ) || echo
-        history -s "$cmd"
-    fi
-
-    # Handle empty input.
-    [[ -z "$cmd" ]] && continue
-
-    # Handle `exit [status]`.
-    if [[ "$cmd" =~ ^exit([[:space:]]+(.*))?$ ]]; then
-        current_status="${BASH_REMATCH[2]:-0}"
-        break;
-    fi
-
-    # Handle built-in commands.
-    if [[ "$cmd" =~ ^\.([[:alnum:]_]+)([[:space:]]+(.+))?$ ]]; then
-        action="${BASH_REMATCH[1]}"
-
-        # Get command arguments (if any).
-        if [[ -n "${BASH_REMATCH[3]}" ]]; then
-            read -ra args <<< "${BASH_REMATCH[3]}"
+        if [[ ! -f "$READX_PATH" ]]; then
+            echo -e "ℹ️  Failed to find $READX. Tab-completion will not be available.\n" >&2
+            unset READX_PATH
         else
-            args=()  # no arguments
+            readonly READX_PATH
         fi
-
-        case "$action" in
-            help)
-                show_commands
-                continue
-                ;;
-            edit|ed)
-                file_path="${args[0]}"
-                edit_file "edit" "$file_path" "${args[@]:1}"
-                continue
-                ;;
-            view|vw)
-                file_path="${args[0]}"
-                edit_file "view" "$file_path" "${args[@]:1}"
-                continue
-                ;;
-            copy|cp)
-                handle_copy args
-                continue
-                ;;
-            copyr|cr)
-                handle_copyr args
-                continue
-                ;;
-            rsync|rs)
-                handle_rsync args
-                continue
-                ;;
-        esac
     fi
 
-    # Handle toggling of auto-ls feature.
-    if [[ "$cmd" == ".ls" ]]; then
-        if (( auto_ls == 0 )); then
-            echo "✅ Auto-ls enabled" >&2
-            auto_ls=1
-            ssh_exec "cd \"$current_dir\" && ls -pC --group-directories-first"
+    # Get local colour settings.
+    local clr0=$(tput sgr0 2>/dev/null) \
+    && local clr1=$(tput setaf 1 2>/dev/null) \
+    && local clr2=$(tput setaf 3 2>/dev/null) \
+    && local clr3=$(tput setaf 6 2>/dev/null)
+
+    # Escaped prompt used, with readx (bash command line input).
+    local prompt_ps1=$( printf \
+        "\[${clr1}\]%s\[${clr0}\].\[${clr2}\]%s\[${clr0}\]:\[${clr3}\]%s\[${clr0}\]\$ " \
+        "$SITE_NAME" "$ENV_ID" "_CWD_"
+    )
+
+    # Get un-escaped prompt, used with `echo` and `read`.
+    local tmp=${prompt_ps1//\\[/}
+    local prompt=${tmp//\\]/}
+
+    # Set up command history behaviour.
+    export HISTFILE="$STORAGE_DIR/$SITE_NAME.$ENV_ID.history"
+    export HISTCONTROL=ignorespace:ignoredups:erasedups
+    history -r
+
+    # Set up initial state.
+    REMOTE_CWD="/code"
+    current_dir="$REMOTE_CWD"
+
+    readonly clr0 clr1 clr2 clr3 prompt prompt_ps1
+
+    local current_status=0
+    local auto_ls=0
+    local cmd
+
+    # Basic environment checks.
+    if ssh_exec "cd $current_dir"; then
+        if ssh_exec "[ -w $current_dir ]"; then
+            echo -e "🟡 $current_dir directory is writable (SFTP mode)\n" >&2
         else
-            echo "🚫 Auto-ls disabled" >&2
-            auto_ls=0
-        fi
-        continue
-    fi
-
-    # Execute a remote command:
-    # Run the command with our environment, current directory and correct initial value for $?
-    ssh_exec_track "export $REMOTE_ENV; cd \"$current_dir\" && bash -c \"exit $current_status\"" "$cmd"
-    current_status=$?
-
-    # Check whether the command changed the current directory.
-    if [[ -n "$REMOTE_CWD"  &&  "$REMOTE_CWD" != "$current_dir" ]]; then
-        current_dir="$REMOTE_CWD"
-
-        # Automatic directory listing if enabled.
-        if (( auto_ls == 1 )); then
-            ssh_exec "cd \"$current_dir\" && ls -pC --group-directories-first"
+            echo -e "🚫 $current_dir directory is read-only (Git mode)\n" >&2
         fi
     fi
 
-done
+    # Create our remote home directory if it doesn't exist.
+    ssh_exec "mkdir -p \"$REMOTE_HOME\""
 
-exit $current_status
+    # --- Main loop ---
+    trap '' SIGINT
+    while true; do
+        if [[ -n "$READX_PATH" ]]; then
+            # readx is available - use it for command input.
+            export READX_EXEC="ssh $SSH_OPTIONS $USER@$HOST 'echo %s | bash'"
+            export REMOTE_ENV CWD="$current_dir"
+            export READX_PROMPT="${prompt_ps1/_CWD_/$current_dir}"
+            export READX_FIRST_TIME="${READX_FIRST_TIME:-1}"
+
+            # Use bash interactive to read command input with completion.
+            cmd=$(/usr/bin/env bash --init-file "$READX_PATH")
+            # Re-display both prompt and input, to mimic standard Bash behaviour.
+            echo "${prompt/_CWD_/$current_dir}$cmd"
+            READX_FIRST_TIME=0
+        else
+            # readx is not available - use `read` for command input.
+            cmd=$(
+                trap - SIGINT
+                bind '"\t":' 2>/dev/null
+                read -e -r -p "${prompt/_CWD_/$current_dir}" cmd && echo $cmd
+            ) || echo
+            history -s "$cmd"
+        fi
+
+        # Handle empty input.
+        [[ -z "$cmd" ]] && continue
+
+        # Handle `exit [status]`.
+        if [[ "$cmd" =~ ^exit([[:space:]]+(.*))?$ ]]; then
+            current_status="${BASH_REMATCH[2]:-0}"
+            break;
+        fi
+
+        # Handle built-in commands.
+        if [[ "$cmd" =~ ^\.([[:alnum:]_]+)([[:space:]]+(.+))?$ ]]; then
+            local action="${BASH_REMATCH[1]}"
+
+            # Get command arguments (if any).
+            if [[ -n "${BASH_REMATCH[3]}" ]]; then
+                read -ra args <<< "${BASH_REMATCH[3]}"
+            else
+                args=()
+            fi
+
+            case "$action" in
+                help)
+                    show_commands
+                    continue
+                    ;;
+                edit|ed)
+                    file_path="${args[0]}"
+                    edit_file "edit" "$file_path" "${args[@]:1}"
+                    continue
+                    ;;
+                view|vw)
+                    file_path="${args[0]}"
+                    edit_file "view" "$file_path" "${args[@]:1}"
+                    continue
+                    ;;
+                copy|cp)
+                    handle_copy args
+                    continue
+                    ;;
+                copyr|cr)
+                    handle_copyr args
+                    continue
+                    ;;
+                rsync|rs)
+                    handle_rsync args
+                    continue
+                    ;;
+            esac
+        fi
+
+        # Handle toggling of auto-ls feature.
+        if [[ "$cmd" == ".ls" ]]; then
+            if (( auto_ls == 0 )); then
+                echo "✅ auto-ls enabled" >&2
+                auto_ls=1
+                ssh_exec "cd \"$current_dir\" && ls -pC --group-directories-first"
+            else
+                echo "🚫 auto-ls disabled" >&2
+                auto_ls=0
+            fi
+            continue
+        fi
+
+        # Execute a remote command:
+        # Run the command with our environment, current directory and correct initial value for $?
+        ssh_exec_track "export $REMOTE_ENV; cd \"$current_dir\"" "$cmd" "$current_status"
+        current_status="$?"
+
+        # Check whether the command changed the current directory.
+        if [[ -n "$REMOTE_CWD"  &&  "$REMOTE_CWD" != "$current_dir" ]]; then
+            current_dir="$REMOTE_CWD"
+
+            # Automatic directory listing if enabled.
+            if (( auto_ls == 1 )); then
+                ssh_exec "cd \"$current_dir\" && ls -pC --group-directories-first"
+            fi
+        fi
+
+    done
+    exit $current_status
+}
+
+interactive
